export const menuItemsData = [
    {
        id: 1,
        name: 'Salada Mediterrânea',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/bigBurger.png',
    },
    {
        id: 2,
        name: 'Salada asiática de verão',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/bowl1.png',
    },
    {
        id: 3,
        name: 'Hambúrguer',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/bowl2.png',
    },
    {
        id: 4,
        name: 'Macarrão ao molho branco',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/bowl3.png',
    },
    {
        id: 5,
        name: 'Macarrão borboleta',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/bowl4.png',
    },
    {
        id: 6,
        name: 'Tigela de frutas toy',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/fruits.png',
    },
    {
        id: 7,
        name: 'Tigela de cereal granola',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/granola cereal bowl.png',
    },
    {
        id: 8,
        name: 'Tigela de palma',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-aa-na-tigela-smoothie-aa-palm-bowl-apple-j-goji-berry-5b306ffe7baf07.9992682215299010545066.png',
    },
    {
        id: 9,
        name: 'Batido de tigela',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-aa-na-tigela-smoothie-breakfast-juice-health-s-acai-bowl-5b11d2604db908.6695630315278946243184.png',
    },
    {
        id: 10,
        name: 'Café da manhã',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-breakfast-cereal-pizza-muesli-meze-vegetarian-cuis-granola-5ac48d852aeb69.1891892315228307251758.png',
    },
    {
        id: 11,
        name: 'Cozinha do Havaí',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-cuisine-of-hawaii-l-l-hawaiian-barbecue-shrimp-gam-frozen-chicken-5b1e62f3a9e035.2766282415287180676958.png',
    },
    {
        id: 12,
        name: 'Frango frito',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-fried-chicken-lemon-chicken-chicken-meat-fine-dining-chicken-meat-5a940a1b75aa22.821205431519651355482.png',
    },
    {
        id: 13,
        name: 'Salada grega',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-greek-salad-fruit-salad-spinach-salad-muesli-vegetable-salad-5a96f429ce9af3.7299622115198423458463.png',
    },
    {
        id: 14,
        name: 'Hamburger',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-hamburger-street-food-seafood-fast-food-delicious-food-5a75083cceaf41.2676743415176192608466.png',
    },
    {
        id: 15,
        name: 'Salada israelense',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-israeli-salad-european-cuisine.png',
    },
    {
        id: 16,
        name: 'Pizza Pasta',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/kisspng-italian-cuisine-pizza-pasta-food-plate-healthy-food-5abb864701e2b7.3892346415222390470077.png',
    },
    {
        id: 17,
        name: 'Pizza',
        info: 'picante com alho e depois frito até a perfeição crocante',
        price: 24,
        img: '/images/data/pizza.png',
    },
];